### ISSUE TITLE
update the package on pub dv

### ISSUE THREAD

**Issue by hatemragab** [SimformSolutionsPvtLtd/audio_waveforms#139]
I can't use the package from pub.dev since this bug 
 #41
Not published Hope you update it as soon as Thanks

**Comment by ujas-m-simformsolutions** [comment]
@hatemragab We have released `1.0.0` to the pub.dev. There are multiple breaking changes so make sure so to check them.

**Comment by zelela** [comment]
1.0.0 release has been published to pub.dev, but I'm still experiencing the same issue #41 Is there anything else I can do to help resolve this issue?

**Comment by Ujas-Majithiya** [comment]
> 1.0.0 release has been published to pub.dev, but I'm still experiencing the same issue #41 Is there anything else I can do to resolve this issue? 

Which flutter version are you using?
