### ISSUE TITLE
PlayerController on iOS plays without sound (physical device only)

### ISSUE THREAD

**Issue by KestasVenslauskas** [SimformSolutionsPvtLtd/audio_waveforms#349]
**Describe the bug**
If a `PlayerController` is used to play audio file it plays without sound. It's waveform is visible and you can seek to parts of the audio but there is no sound.
Once you use `RecordController` and record something then `PlayerController` starts to work with sound.
This bug happens on physical iOS device only. Tried few different ones the outcome is the same.

**To Reproduce**
1. Run the example app
2. Before you record anything press play on any message
3. Observe the problem 
4. Additionally - start & stop recording and then try playing any audio again.
5. Problem is gone.

**Expected behavior**
Player should play from cold start with sound.

**Smartphone (please complete the following information):**
- Device: iPhone6, iPhone10
- OS: iOS16.0, iOS18.0

**Additional context**
This bug happens on physical iOS devices only.

**Comment by jay-simformsolutions** [comment]
Hi @KestasVenslauskas I have tried your issue from iOS 15 to 17 version but still it's not reproducible. Can you please share minimal reproducible code or more clarification on your issue?

iOS version: 16
device: iPhone 12


https://github.com/user-attachments/assets/e4cc8d23-844c-4a70-b80e-5da29d03fe08

**Comment by KestasVenslauskas** [comment]
I am able to reproduce it on the example project no need to any other repo. Not sure what is the trigger for the cause, it's important that you do not try to record before you press play. Even after you pressed record you have to re-build the app, flutter restart is not enough you have to kill the app and this issue should be present on first run

**Comment by jay-simformsolutions** [comment]
As you can see in the shared video, we are unable to reproduce the issue, so we’re unable to dig deeper. Just to double-check, are any other apps playing sound? If that is the case then you may try to use ios AudioSession to override this behavior.

**Comment by suesitran** [comment]
I second this issue. The behaviour is exactly as described, 

When I use player controller, there's no sound although volume is max and waveform is animated.

**But if I turn to record a short audio, then return to play audio, then audio works as normal.**

**Comment by lqchuong** [comment]
I have the same issue on iOS device

https://github.com/user-attachments/assets/8004f2d8-c386-4adf-93d5-cbb6d91600ed

**Comment by KestasVenslauskas** [comment]
@jay-simformsolutions no luck of reproducing?

**Comment by jay-simformsolutions** [comment]
@KestasVenslauskas Yes, this issue is still not reproducible on our end. We will try your steps on different devices and update you once we get any hints about this issue.

If you provide more details on this issue then it will be very helpful for us.

**Comment by suesitran** [comment]
I tried to run the example app in my ipad, and here is the screen recording. I turn on sound recording as well to record the sound, both from my voice and from the audio output.

There's no error printed out

https://github.com/user-attachments/assets/62f74483-c459-4e5c-95e7-78a4568f2bf1

Flutter doctor
```
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.0 23A344 darwin-arm64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.92.2)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
```

Pod version: 1.13.0
Dart version: Dart SDK version: 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64"
iPadOS: 18.0.1

**Comment by jay-simformsolutions** [comment]
@KestasVenslauskas, @suesitran, @lqchuong can you please ensure that your device is not in **silent mode**?

**Comment by lqchuong** [comment]
Sure sir, my device is not on silent mode.

**Comment by KestasVenslauskas** [comment]
It's not, and bug is consistent on every device I tried

**Comment by thenartus** [comment]
I confirm my device is not in silent mode

**Comment by suesitran** [comment]
I confirm that my device is not in silent mode

**Comment by lqchuong** [comment]
@jay-simformsolutions  any luck on this issue? :(

**Comment by jay-simformsolutions** [comment]
@lqchuong, @KestasVenslauskas, @suesitran  can you please try this branch?

```
audio_waveforms:
  git:
    url: https://github.com/SimformSolutionsPvtLtd/audio_waveforms/tree/fix/ios_audio_play_without_sound
```

**Comment by suesitran** [comment]
@jay-simformsolutions yes that branch works, here is my pubspec.yaml

```
  audio_waveforms:
    git:
      url: https://github.com/SimformSolutionsPvtLtd/audio_waveforms.git
      ref: fix/ios_audio_play_without_sound
```

**Comment by lqchuong** [comment]
@jay-simformsolutions yupp, that works for me. I think a lot of people have this issue but they don't really realize it, pls merge it asap. Thanks so muchh

**Comment by ujas-m-simformsolutions** [comment]
This fix has been merged into the `main` branch. However, since we couldn’t reproduce the issue on multiple devices, and no other users reported it, we’ve decided not to apply this fix by default. This approach maintains consistency with previous behavior and avoids overriding the user’s existing AudioSession configuration.

To enable this fix, set the following:
```
playerController.overrideAudioSession = true;
```

**Comment by yagoquesadafloriach** [comment]
> This fix has been merged into the `main` branch. However, since we couldn’t reproduce the issue on multiple devices, and no other users reported it, we’ve decided not to apply this fix by default. This approach maintains consistency with previous behavior and avoids overriding the user’s existing AudioSession configuration.
> 
> To enable this fix, set the following:
> 
> ```
> playerController.overrideAudioSession = true;
> ```

I got the same issue trying on my iPhone physical device
- **Device:** iPhone 12
- **iOS Version:** 17.6.1

**Comment by raulmabe-labhouse** [comment]
> playerController.overrideAudioSession = true;

On my physical device this doesn't fix the issue. It works when my bluetooth headphones are connected, but otherwise it does not make any sound even though my volume is at max.

Model iPhone 14 Pro
iOS 17.5.1
Flutter Version is 3.24.0

**Comment by Ujas-Majithiya** [comment]
@raulmabe-labhouse As mentioned in docs of `overrideAudioSession`, if you set it to true we will set Audio session category as .playback and mode will be default since you have some different requirement, you will have to set your  own audio session as you did with your shared code.

**Comment by raulmabe-labhouse** [comment]
@Ujas-Majithiya I understand I have a different config that what `overrideAudioSession` does. I still do not understand why `playback` didn't output any sound on my physical device while on other devices it worked well, that's why I shared my experience.
